#!/bin/sh

# since the ELF interpreter (=ld-linux.so) is at a relative path we must set the
# current directory to the mounted root of the AppDir (=${APPDIR}) for the whole runtime

cd "${APPDIR}"

"${APPDIR}/usr/bin/bash" "${APPDIR}/usr/bin/sysrescueusbwriter" "$@"
RET=$?

cd "${OWD}"

exit $RET
