#!/bin/sh

# since the ELF interpreter (=ld-linux.so) is at a relative path we must set the
# current directory to the mounted root of the AppDir (=${APPDIR}) for the whole runtime

pushd "${APPDIR}" >/dev/null

"${APPDIR}/usr/bin/bash" "${APPDIR}/usr/bin/sysrescueusbwriter" "$@"
RET=$?

popd >/dev/null

exit $RET
